#!/bin/bash

# Build docker images
buildc ()
{
  docker build . --tag zfp-main -f docker-main
}

# remove all stopped containers
killc ()
{
  docker rm $(docker ps -a -q)
}

# start analysis
startc ()
{
  docker run -t -d -v $(pwd)/dataset:/host-storage -v $(pwd)/src:/src --name zfp-main zfp-main
  MAIN_ID=$(docker ps -qf "name=^zfp-main$")
}

# attach to container terminal
attachc ()
{
  docker exec -it $MAIN_ID /bin/bash  
}

# tar the llvm folders under install since we untar it in docker-main
tar_llvm ()
{
  tar -czvf ./installs/llvm/llvm-3.8.0.src.tar.gz ./installs/llvm/llvm-3.8.0.src
}

# remove zfp metadata 
rmm ()
{
  rm -rf zfp-0.*
}

# stop and remove all running docker containers
docker_clean ()
{
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
}

# restart docker
# https://stackoverflow.com/questions/31365827/cannot-stop-or-restart-a-docker-container
docker_fresh ()
{
  sudo systemctl restart docker.socket docker.service
}

# detach from container terminal: Ctrl-P n Ctrl-Q
# how to de-attach: https://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process


# count line numbers in file excluding comments and spaces
countlines()
{
  # to remove blank lines: 
  # https://stackoverflow.com/questions/114814/count-non-blank-lines-of-code-in-bash
  # to remove C comments:
  # https://unix.stackexchange.com/questions/317795/remove-comments-in-a-c-file
  perl -0777 -pe 's,/\*.*?\*/,,gs' ${1} | sed '/^\s*$/d' | wc -l
}
