#!/bin/bash

# Build docker images
zfpbuild ()
{
  docker build . --tag zfp -f dockerfile-zfp
}

# start analysis
# testing
zfpstarttest ()
{
  docker run -t -d -v $(pwd)/scripts:/scripts -v $(pwd)/dataset:/dataset -v $(pwd)/src:/src --name zfp zfp
  MAIN_ID=$(docker ps -qf "name=^zfp$")
  docker exec -it $MAIN_ID /bin/bash  
}

# start analysis
# production
zfpstart ()
{
  docker run -t -d -v $(pwd)/scripts:/scripts -v $(pwd)/dataset:/dataset --name zfp zfp
  MAIN_ID=$(docker ps -qf "name=^zfp$")
  docker exec -it $MAIN_ID /bin/bash  
}

# remove zfp metadata 
zfprm ()
{
  rm -rf zfp-0.*
}

# remove all stopped containers
dockerrm ()
{
  docker rm $(docker ps -a -q)
}
# stop and remove all running docker containers
dockerclean ()
{
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
}

# restart docker
# https://stackoverflow.com/questions/31365827/cannot-stop-or-restart-a-docker-container
dockerfresh ()
{
  sudo systemctl restart docker.socket docker.service
}

# detach from container terminal: Ctrl-P and Ctrl-Q
# how to de-attach: https://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process


# count line numbers in file excluding comments and spaces
countlines()
{
  # to remove blank lines: 
  # https://stackoverflow.com/questions/114814/count-non-blank-lines-of-code-in-bash
  # to remove C comments:
  # https://unix.stackexchange.com/questions/317795/remove-comments-in-a-c-file
  perl -0777 -pe 's,/\*.*?\*/,,gs' ${1} | sed '/^\s*$/d' | wc -l
}
