#!/bin/bash

# remove all stopped containers
drm ()
{
  docker rm $(docker ps -a -q)
}
# stop and remove all running docker containers
dsrm ()
{
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
}

# restart docker
# https://stackoverflow.com/questions/31365827/cannot-stop-or-restart-a-docker-container
dfresh ()
{
  sudo systemctl restart docker.socket docker.service
}

### Docker 
# detach from container terminal: Ctrl-P and Ctrl-Q
# how to de-attach: https://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process

### Flake8
# pretty print number of violations:
#     flake8 --statistics core/*
# all locations of a specific violation:
#     flake8 --select W293 core/* 

# count line numbers in file excluding comments and spaces
clines ()
{
  # to remove blank lines: 
  # https://stackoverflow.com/questions/114814/count-non-blank-lines-of-code-in-bash
  # to remove C comments:
  # https://unix.stackexchange.com/questions/317795/remove-comments-in-a-c-file
  perl -0777 -pe 's,/\*.*?\*/,,gs' ${1} | sed '/^\s*$/d' | wc -l
}

# delete trailing whitespaces from a file
rmt ()
{
  sed --in-place 's/[[:space:]]\+$//' ${1}
}
