#!/bin/bash

# Build docker images
zfpbuild ()
{
  docker build . --tag zfp -f dockerfile-zfp
}

# start analysis
# testing
zfpstarttest ()
{
  if [ $# -eq 0 ]
    then
      echo "Need to supply relative path to folder containing code to obfuscate"
  else
    docker run -t -d -v $(pwd)/scripts:/scripts -v $(pwd)/${1}:/${1} -v $(pwd)/src:/src --name zfp zfp
    docker exec -it zfp /bin/bash  
  fi
}

# start analysis
# production
zfpstart ()
{
  if [ $# -eq 0 ]
    then
      echo "Need to supply relative path to folder containing code to obfuscate"
  else
    docker run -t -d -v $(pwd)/scripts:/scripts -v $(pwd)/${1}:/${1} --name zfp zfp
    docker exec -it zfp /bin/bash  
  fi
}

# attach to container after detach
zfpattach ()
{
  docker exec -it zfp /bin/bash
}

# remove zfp metadata 
zfprm ()
{
  rm -rf zfp-0.*
}

# remove all stopped containers
dockerrm ()
{
  docker rm $(docker ps -a -q)
}
# stop and remove all running docker containers
dockerclean ()
{
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
}

# restart docker
# https://stackoverflow.com/questions/31365827/cannot-stop-or-restart-a-docker-container
dockerfresh ()
{
  sudo systemctl restart docker.socket docker.service
}
